name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: 89.47.162.195
        USERNAME: jesdav
        PORT: 22
        PASSWORD: CINthya2218*
      with:
        source: "."
        target: "/home/vkm/domains/nagaira.com/public_html/etc/pruebas"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        HOST: 89.47.162.195
        USERNAME: jesdav
        PORT: 22
        PASSWORD: CINthya2218*
        script: ls
